In [3]:
import numpy as np

In [10]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [12]:
a[0]

1

In [14]:
import time
import sys

In [18]:
b=range(1000)
print(sys.getsizeof(5)*len(b))

28000


In [20]:
c=np.arange(1000)
print(c.size*c.itemsize)

4000


In [22]:
size=100000

In [24]:
L1=range(size)
L2=range(size)
A1=np.arange(size)
A2=np.arange(size)

In [70]:
start=time.time()
result=[(x+y) for x,y in zip(L1,L2)]
print("python list took:",(time.time()-start)*1000)


python list took: 42.55533218383789


In [32]:
start=time.time()
result=A1+A2
print("Python Numpy took:",(time.time()-start)*1000)

Python Numpy took: 7.31205940246582


In [36]:
a=np.array([[1,2],[3,4],[5,6]])
a           

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
a.itemsize

4

In [40]:
a.ndim

2

In [54]:
a.shape
a.dtype

dtype('float64')

In [56]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
a.itemsize

8

In [58]:
a.shape

(3, 2)

In [66]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.complex128)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])